github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/sap-machine","gcr.io/paketo-buildpacks/sap-machine"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jdk-.+_linux-x64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(17.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 17
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jre-.+_linux-x64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(17.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jdk-.+_linux-x64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(21.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 21
  id:              jre
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jre-.+_linux-x64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(21.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 24
  id:              jdk
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jdk-.+_linux-x64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(24.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JRE 24
  id:              jre
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jre-.+_linux-x64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(24.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
  
# ARM64
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jdk-.+_linux-aarch64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(17.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: "arm64"
- name:            JRE 17 ARM64
  id:              jre
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jre-.+_linux-aarch64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(17.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: "arm64"
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jdk-.+_linux-aarch64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(21.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: "arm64"
- name:            JRE 21 ARM64
  id:              jre
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jre-.+_linux-aarch64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(21.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: "arm64"
- name:            JDK 24 ARM64
  id:              jdk
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jdk-.+_linux-aarch64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(24.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: "arm64"
- name:            JRE 24 ARM64
  id:              jre
  version_pattern: "24\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:                    sapmachine-jre-.+_linux-aarch64_bin.tar.gz
    owner:                   SAP
    repository:              SapMachine
    tag_filter:              sapmachine-(24.*)
    latest_by_creation_time: true
    token:                   ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch: "arm64"
