# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the SAP Machine implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/sap-machine"
  id = "paketo-buildpacks/sap-machine"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for SapMachine"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/sap-machine/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@17.0.20?arch=amd64"
    sha256 = "86d8c30a4dcc31921b921deb872b2217364e3bbf695f3a854feeac12ec628eb9"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.1.tar.gz"
    source-sha256 = "7583784f29c77881ad836481c5476e8bbea7b05d39a637c5c604874ef9c825db"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20.1/sapmachine-jdk-17.0.20.1_linux-x64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@17.0.20?arch=amd64"
    sha256 = "133f80ba8db1403a49831ae59392b74670ab0444018d40be5aa16458c3968f8a"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.1.tar.gz"
    source-sha256 = "7583784f29c77881ad836481c5476e8bbea7b05d39a637c5c604874ef9c825db"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20.1/sapmachine-jre-17.0.20.1_linux-x64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@21.0.12?arch=amd64"
    sha256 = "e51e90fa8111f6293b69888d7c6b6cf9791942c84327057a2f899c619c3f7cb8"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.1.tar.gz"
    source-sha256 = "436e65fa04afed38a59abb8b5794c1687b27fb00becf67d7f0839b07cbe200fb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12.1/sapmachine-jdk-21.0.12.1_linux-x64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@21.0.12?arch=amd64"
    sha256 = "be23fbde203788c43a238b87971af46f17213b3357d274c8fc48632ec74b1619"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.1.tar.gz"
    source-sha256 = "436e65fa04afed38a59abb8b5794c1687b27fb00becf67d7f0839b07cbe200fb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12.1/sapmachine-jre-21.0.12.1_linux-x64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@25.0.4?arch=amd64"
    sha256 = "d637b0e791f59af16f3a48ccb1e509c37cded76d8cc2c0aaf9045c13351142a3"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.1.tar.gz"
    source-sha256 = "1e43bd1d778000a792a361f0db971a1880548a80afc988ece29877208fddd043"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4.1/sapmachine-jdk-25.0.4.1_linux-x64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@25.0.4?arch=amd64"
    sha256 = "c70a97647a0045142642964f642ccf9157d3c49f298e9d9c6303fdb43a49ff4f"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.1.tar.gz"
    source-sha256 = "1e43bd1d778000a792a361f0db971a1880548a80afc988ece29877208fddd043"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4.1/sapmachine-jre-25.0.4.1_linux-x64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@17.0.20?arch=arm64"
    sha256 = "759355e85af49a5b51a8f044bfa7c04c3900e88574efaec18d8b9bc3ec6be7de"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.1.tar.gz"
    source-sha256 = "7583784f29c77881ad836481c5476e8bbea7b05d39a637c5c604874ef9c825db"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20.1/sapmachine-jdk-17.0.20.1_linux-aarch64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@17.0.20?arch=arm64"
    sha256 = "45fc8b54d3c507a9f3f900d334c5fd7f6db840a939b18dfb6df60f907918f83a"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.1.tar.gz"
    source-sha256 = "7583784f29c77881ad836481c5476e8bbea7b05d39a637c5c604874ef9c825db"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20.1/sapmachine-jre-17.0.20.1_linux-aarch64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@21.0.12?arch=arm64"
    sha256 = "fc502287777e3b10a5624367fbcfb944f94b578aaed29851628ee03b6e07a4b2"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.1.tar.gz"
    source-sha256 = "436e65fa04afed38a59abb8b5794c1687b27fb00becf67d7f0839b07cbe200fb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12.1/sapmachine-jdk-21.0.12.1_linux-aarch64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@21.0.12?arch=arm64"
    sha256 = "2af69647269ace78d961a9de35a88e2f8eeecff3bbeb6e28df29fadd2090e94d"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.1.tar.gz"
    source-sha256 = "436e65fa04afed38a59abb8b5794c1687b27fb00becf67d7f0839b07cbe200fb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12.1/sapmachine-jre-21.0.12.1_linux-aarch64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@25.0.4?arch=arm64"
    sha256 = "43778f142f87694f235d3a46f32cd36999b697918db5f53ae549194177177d44"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.1.tar.gz"
    source-sha256 = "1e43bd1d778000a792a361f0db971a1880548a80afc988ece29877208fddd043"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4.1/sapmachine-jdk-25.0.4.1_linux-aarch64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@25.0.4?arch=arm64"
    sha256 = "52b213fba8a5b4bf7564c16c6cec35de8fab5b1c1f538c504bf92607c2c63227"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.1.tar.gz"
    source-sha256 = "1e43bd1d778000a792a361f0db971a1880548a80afc988ece29877208fddd043"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4.1/sapmachine-jre-25.0.4.1_linux-aarch64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
