# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the SAP Machine implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/sap-machine"
  id = "paketo-buildpacks/sap-machine"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for SapMachine"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/sap-machine/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@17.0.20?arch=amd64"
    sha256 = "0219434d3528a6092add15926d2df7d10c55a8032a318ef3f7875fcb407ff4bc"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.tar.gz"
    source-sha256 = "0aeeb1625bbe7ccf3f7b5135550d5ac87dadc6a1375dbb021035bc47882795f7"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20/sapmachine-jdk-17.0.20_linux-x64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@17.0.20?arch=amd64"
    sha256 = "133f80ba8db1403a49831ae59392b74670ab0444018d40be5aa16458c3968f8a"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.1.tar.gz"
    source-sha256 = "7583784f29c77881ad836481c5476e8bbea7b05d39a637c5c604874ef9c825db"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20.1/sapmachine-jre-17.0.20.1_linux-x64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@21.0.12?arch=amd64"
    sha256 = "d15178465ebbc3a784f394611e4a5a9e7290049952dda55751f0056c6bf3459c"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.tar.gz"
    source-sha256 = "124cc90a2821d53d06d9a17ee5f69ddb24dd624610eae940442bb46d088d2396"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12/sapmachine-jdk-21.0.12_linux-x64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@21.0.12?arch=amd64"
    sha256 = "1054f195874edc90920d3428da874b2cebd150169fe650018bfc62ddee06bbaa"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.tar.gz"
    source-sha256 = "124cc90a2821d53d06d9a17ee5f69ddb24dd624610eae940442bb46d088d2396"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12/sapmachine-jre-21.0.12_linux-x64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@25.0.4?arch=amd64"
    sha256 = "fc3851ec41715a4fccb30820a10c8ceaac161175567ea784de7dffae47eedc3a"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.tar.gz"
    source-sha256 = "d98ef346f7df005e51a159584a7609137b30417d20a5baf47001010fa0035fbb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4/sapmachine-jdk-25.0.4_linux-x64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@25.0.4?arch=amd64"
    sha256 = "45822a0180c0b1b5afd789a0d4bc3442d6841605e3aff87c731156e3ed73d39c"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.tar.gz"
    source-sha256 = "d98ef346f7df005e51a159584a7609137b30417d20a5baf47001010fa0035fbb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4/sapmachine-jre-25.0.4_linux-x64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@17.0.20?arch=arm64"
    sha256 = "267791d3d14c00af4596949642c6849e72d6ecef37d6a651d0cea81c3e849f2c"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.tar.gz"
    source-sha256 = "0aeeb1625bbe7ccf3f7b5135550d5ac87dadc6a1375dbb021035bc47882795f7"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20/sapmachine-jdk-17.0.20_linux-aarch64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.20:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@17.0.20?arch=arm64"
    sha256 = "e4c7213762882a02b892f615ed8606a3ee20567d25444e00f52ebf08ef5634f3"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.20.tar.gz"
    source-sha256 = "0aeeb1625bbe7ccf3f7b5135550d5ac87dadc6a1375dbb021035bc47882795f7"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.20/sapmachine-jre-17.0.20_linux-aarch64_bin.tar.gz"
    version = "17.0.20"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@21.0.12?arch=arm64"
    sha256 = "d6e0093800ff01a29af672806434e4dbe04c2b7d343b740d6cb94fab83bc23dd"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.tar.gz"
    source-sha256 = "124cc90a2821d53d06d9a17ee5f69ddb24dd624610eae940442bb46d088d2396"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12/sapmachine-jdk-21.0.12_linux-aarch64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.12:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@21.0.12?arch=arm64"
    sha256 = "2af69647269ace78d961a9de35a88e2f8eeecff3bbeb6e28df29fadd2090e94d"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.12.1.tar.gz"
    source-sha256 = "436e65fa04afed38a59abb8b5794c1687b27fb00becf67d7f0839b07cbe200fb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.12.1/sapmachine-jre-21.0.12.1_linux-aarch64_bin.tar.gz"
    version = "21.0.12"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@25.0.4?arch=arm64"
    sha256 = "b9e14cbc9e66714162d9b13b8fd9e6568e9d8db5f518988f58e8256b9e677171"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.tar.gz"
    source-sha256 = "d98ef346f7df005e51a159584a7609137b30417d20a5baf47001010fa0035fbb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4/sapmachine-jdk-25.0.4_linux-aarch64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.4:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@25.0.4?arch=arm64"
    sha256 = "58c98ba9247a7e018f75807ca156a76858f967acc408c35a4802183970773996"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.4.tar.gz"
    source-sha256 = "d98ef346f7df005e51a159584a7609137b30417d20a5baf47001010fa0035fbb"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.4/sapmachine-jre-25.0.4_linux-aarch64_bin.tar.gz"
    version = "25.0.4"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
