# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the SAP Machine implementations of JREs and JDKs"
  homepage = "https://github.com/paketo-buildpacks/sap-machine"
  id = "paketo-buildpacks/sap-machine"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for SapMachine"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/sap-machine/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.19:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@17.0.19?arch=amd64"
    sha256 = "6fe7413b5fb62d8307249987fc2863dfa817b54755a4b865e1b4215fbaa7d242"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.19.tar.gz"
    source-sha256 = "c6d328261e8a36b8e5fafdf2dcc3a567dea5b3a7cb151dcc621632b975ce0a67"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.19/sapmachine-jdk-17.0.19_linux-x64_bin.tar.gz"
    version = "17.0.19"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.19:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@17.0.19?arch=amd64"
    sha256 = "133d93f4e1995fd1913c8b159096ce60367af7cf1c2a56422e695720b9925a9e"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.19.tar.gz"
    source-sha256 = "c6d328261e8a36b8e5fafdf2dcc3a567dea5b3a7cb151dcc621632b975ce0a67"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.19/sapmachine-jre-17.0.19_linux-x64_bin.tar.gz"
    version = "17.0.19"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.11:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@21.0.11?arch=amd64"
    sha256 = "8c3f89840069bcca458664ff967c878a2711cf826d4b1c03eaf7b5df632e7079"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.11.tar.gz"
    source-sha256 = "a6c193b37881393f02477d2f77856d258ba29319cbb20327213956ffeba3fbc0"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.11/sapmachine-jdk-21.0.11_linux-x64_bin.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.11:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@21.0.11?arch=amd64"
    sha256 = "9af6e370c4457a155bfe0b6bdf7fb787a1385636e65fd49b35d6c5630d4d2589"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.11.tar.gz"
    source-sha256 = "a6c193b37881393f02477d2f77856d258ba29319cbb20327213956ffeba3fbc0"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.11/sapmachine-jre-21.0.11_linux-x64_bin.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.3:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@25.0.3?arch=amd64"
    sha256 = "7b451a32c231384aa867dcd91ce9d71866fafc18182300e38d7359a18b1fd6ce"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.3.tar.gz"
    source-sha256 = "466f2a5159fbbcc3e2d4fdf72d9884723f045963144b7f657b9309898e30530c"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.3/sapmachine-jdk-25.0.3_linux-x64_bin.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.3:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@25.0.3?arch=amd64"
    sha256 = "1a0c425ebcc41070dbd6203560ae60c62c5d1e7e03006d93081306d472e236a0"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.3.tar.gz"
    source-sha256 = "466f2a5159fbbcc3e2d4fdf72d9884723f045963144b7f657b9309898e30530c"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.3/sapmachine-jre-25.0.3_linux-x64_bin.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.18:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@17.0.18?arch=arm64"
    sha256 = "c1aef687645489b2ac695f14ed05da44be1daacc22889dd7b5f63030e6768ca2"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.18.tar.gz"
    source-sha256 = "b43abae4ecf98abc31dce2f346c92e0a37d9e16331ee7e7094885ae2242180dc"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.18/sapmachine-jdk-17.0.18_linux-aarch64_bin.tar.gz"
    version = "17.0.18"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.19:*:*:*:*:*:*:*"]
    deprecation_date = "2026-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@17.0.19?arch=arm64"
    sha256 = "5d442003ca036e2b10eb8b292e651f9f020d079de1a4176d9216dc9b800ff2ce"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-17.0.19.tar.gz"
    source-sha256 = "c6d328261e8a36b8e5fafdf2dcc3a567dea5b3a7cb151dcc621632b975ce0a67"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-17.0.19/sapmachine-jre-17.0.19_linux-aarch64_bin.tar.gz"
    version = "17.0.19"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.11:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@21.0.11?arch=arm64"
    sha256 = "8a4e2e4e24204a90dfd66096937259b4347ce16e472beafa1e8948d9c5cbc178"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.11.tar.gz"
    source-sha256 = "a6c193b37881393f02477d2f77856d258ba29319cbb20327213956ffeba3fbc0"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.11/sapmachine-jdk-21.0.11_linux-aarch64_bin.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.11:*:*:*:*:*:*:*"]
    deprecation_date = "2028-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@21.0.11?arch=arm64"
    sha256 = "76323acd4cb41c741698d4900b9bd36cf07130b211e2bdb4762b84d74c4c4f12"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-21.0.11.tar.gz"
    source-sha256 = "a6c193b37881393f02477d2f77856d258ba29319cbb20327213956ffeba3fbc0"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-21.0.11/sapmachine-jre-21.0.11_linux-aarch64_bin.tar.gz"
    version = "21.0.11"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.3:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jdk"
    name = "SapMachine JDK"
    purl = "pkg:generic/sap-machine-jdk@25.0.3?arch=arm64"
    sha256 = "a6e6d8352ae14daeeeaf971415e5b02fbdd96eeff74f2d1632051101680216d3"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.3.tar.gz"
    source-sha256 = "466f2a5159fbbcc3e2d4fdf72d9884723f045963144b7f657b9309898e30530c"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.3/sapmachine-jdk-25.0.3_linux-aarch64_bin.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.3:*:*:*:*:*:*:*"]
    deprecation_date = "2030-09-30T00:00:00Z"
    id = "jre"
    name = "SapMachine JRE"
    purl = "pkg:generic/sap-machine-jre@25.0.3?arch=arm64"
    sha256 = "9d90c1f25bdb582b84ebe50c5c4b90a253323ca4a10f06a26ea409e58e8e4fe2"
    source = "https://github.com/SAP/SapMachine/archive/refs/tags/sapmachine-25.0.3.tar.gz"
    source-sha256 = "466f2a5159fbbcc3e2d4fdf72d9884723f045963144b7f657b9309898e30530c"
    stacks = ["*"]
    uri = "https://github.com/SAP/SapMachine/releases/download/sapmachine-25.0.3/sapmachine-jre-25.0.3_linux-aarch64_bin.tar.gz"
    version = "25.0.3"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
